In [251]:
import pandas as pd
from datetime import datetime, timedelta
pd.set_option('display.max_columns', 100)

df = pd.read_excel("data/khh1005.xlsx")
#把以船舶為表頭改以用拖船為表頭
df_add = df.dropna(subset = ['tug2_no'])
df_add2 = df.dropna(subset = ['tug3_no'])

df_add['tug1_no'] = df_add['tug2_no']
df_add2['tug1_no'] = df_add2['tug3_no']

df_add = df_add.drop(columns = ['tug2_no','tug3_no'])
df_add2 = df_add2.drop(columns = ['tug2_no','tug3_no'])
df = df.drop(columns = ['tug2_no','tug3_no'])
df = pd.concat([df,df_add,df_add2],ignore_index=True)
df = df.sort_values(by='start_time')
cols = df.columns.tolist()
cols = ['tug1_no',
 'ship_no',
 'sailing_status',
 'min_work_time',
 'max_work_time',
 'mean_work_time',
 'start_time',
 'min_end_time',
 'max_end_time',
 'pilot_ready_time',
 'pilot_wait_time',
 'port',
 'place1',
 'place2',
 'pilot1',
 'pilot2',
 'tug_cnt',
 'total_weight',
 'front_weight',
 'back_weight',
 'weight_level',
 'pier_info',
 'dist',
 'wind',
 'park',
 'reverse',
 'seven',
 'day',
 'avg_hp']
df = df[cols]
df.rename(columns={"tug1_no" : "tug"}, inplace=True)
df.dropna(subset = ['tug','place2'])
df = df.reset_index()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

,index,tug,ship_no,sailing_status,min_work_time,max_work_time,mean_work_time,start_time,min_end_time,max_end_time,pilot_ready_time,pilot_wait_time,port,place1,place2,pilot1,pilot2,tug_cnt,total_weight,front_weight,back_weight,weight_level,pier_info,dist,wind,park,reverse,seven,day,avg_hp
0,0,109.0,50091,O,4,4,4,2017-01-01 00:26:00,2017-01-01 00:30:00,2017-01-01 00:30:00,2017-01-01 00:26:00,0,1.0,NaN,1066,100,NaN,1,6094,6.00,7.00,2,0,4968.093286,0.150000,O,0,0,0,3200.0
1,1,321.0,308684,I,52,52,52,2017-01-01 01:38:00,2017-01-01 02:30:00,2017-01-01 02:30:00,2017-01-01 01:34:00,4,1.0,NaN,1058,82,NaN,1,16232,6.00,7.00,4,0,3879.059264,1.000000,O,0,0,0,3200.0
2,2,171.0,46698,I,27,27,27,2017-01-01 01:38:00,2017-01-01 02:05:00,2017-01-01 02:05:00,2017-01-01 01:30:00,8,2.0,NaN,1079,74,NaN,1,27968,10.00,10.00,4,0,1502.675679,1.000000,L,0,0,0,5200.0
3,5,165.0,376574,O,10,10,10,2017-01-01 02:05:00,2017-01-01 02:15:00,2017-01-01 02:15:00,2017-01-01 01:48:00,17,2.0,NaN,1099,93,NaN,1,2440,5.20,6.00,1,0,3259.695637,0.750000,O,0,0,0,4200.0
4,32219,171.0,57126,I,24,29,26,2017-01-01 02:16:00,2017-01-01 02:40:00,2017-01-01 02:45:00,2017-01-01 02:11:00,5,2.0,NaN,1109,98,76.0,2,108069,11.50,11.70,8,0,1033.162198,0.750000,R,0,0,0,5200.0
5,4,172.0,57126,I,24,29,26,2017-01-01 02:16:00,2017-01-01 02:40:00,2017-01-01 02:45:00,2017-01-01 02:11:00,5,2.0,NaN,1109,98,76.0,2,108069,11.50,11.70,8,0,1033.162198,0.750000,R,0,0,0,5200.0
6,32218,109.0,326585,I,34,34,34,2017-01-01 02:21:00,2017-01-01 02:55:00,2017-01-01 02:55:00,2017-01-01 02:16:00,5,2.0,NaN,1102,102,NaN,2,8562,4.00,5.00,2,0,2785.267130,0.750000,O,0,0,0,3700.0
7,3,163.0,326585,I,34,34,34,2017-01-01 02:21:00,2017-01-01 02:55:00,2017-01-01 02:55:00,2017-01-01 02:16:00,5,2.0,NaN,1102,102,NaN,2,8562,4.00,5.00,2,0,2785.267130,0.750000,O,0,0,0,3700.0
8,8,165.0,1066,O,17,17,17,2017-01-01 02:43:00,2017-01-01 03:00:00,2017-01-01 03:00:00,2017-01-01 02:29:00,14,2.0,NaN,1076,97,NaN,1,4165,3.00,4.00,1,0,995.490209,0.750000,O,0,0,0,4200.0
9,7,171.0,356204,I,42,42,42,2017-01-01 02:58:00,2017-01-01 03:40:00,2017-01-01 03:40:00,2017-01-01 02:53:00,5,2.0,NaN,1105,67,NaN,2,31534,6.00,8.00,5,0,2073.646410,0.750000,L,1,0,0,5200.0
10,32220,172.0,356204,I,42,42,42,2017-01-01 02:58:00,2017-01-01 03:40:00,2017-01-01 03:40:00,2017-01-01 02:53:00,5,2.0,NaN,1105,67,NaN,2,31534,6.00,8.00,5,0,2073.646410,0.750000,L,1,0,0,5200.0
11,6,145.0,348163,T,38,38,38,2017-01-01 03:02:00,2017-01-01 03:40:00,2017-01-01 03:40:00,2017-01-01 03:02:00,0,NaN,1028.0,4031,79,NaN,1,2829,3.60,4.20,1,2,508.713096,0.750000,O,0,0,0,1800.0
12,9,163.0,2607,O,12,12,12,2017-01-01 03:48:00,2017-01-01 04:00:00,2017-01-01 04:00:00,2017-01-01 03:48:00,0,1.0,NaN,1064,70,NaN,1,17751,7.00,8.00,4,0,4627.450322,0.750000,L,1,0,0,4200.0
13,12,109.0,25313,O,26,31,28,2017-01-01 04:24:00,2017-01-01 04:50:00,2017-01-01 04:55:00,2017-01-01 04:11:00,13,2.0,NaN,1117,80,NaN,2,17887,7.00,8.00,4,0,824.142563,0.850000,O,0,0,0,3700.0
14,32222,165.0,25313,O,26,31,28,2017-01-01 04:24:00,2017-01-01 04:50:00,2017-01-01 04:55:00,2017-01-01 04:11:00,13,2.0,NaN,1117,80,NaN,2,17887,7.00,8.00,4,0,824.142563,0.850000,O,0,0,0,3700.0
15,11,171.0,43184,I,36,41,38,2017-01-01 04:59:00,2017-01-01 05:35:00,2017-01-01 05:40:00,2017-01-01 04:52:00,7,2.0,NaN,1065,88,NaN,2,20569,9.20,9.50,4,0,1931.993135,0.850000,R,0,0,0,5200.0
16,32221,172.0,43184,I,36,41,38,2017-01-01 04:59:00,2017-01-01 05:35:00,2017-01-01 05:40:00,2017-01-01 04:52:00,7,2.0,NaN,1065,88,NaN,2,20569,9.20,9.50,4,0,1931.993135,0.850000,R,0,0,0,5200.0
17,10,245.0,364401,I,19,19,19,2017-01-01 05:01:00,2017-01-01 05:20:00,2017-01-01 05:20:00,2017-01-01 04:57:00,4,1.0,NaN,1045,61,NaN,1,2479,3.60,4.00,1,0,2059.012837,0.400000,O,0,0,0,2400.0
18,13,163.0,35629,I,29,29,29,2017-01-01 05:31:00,2017-01-01 06:00:00,2017-01-01 06:00:00,2017-01-01 05:24:00,7,2.0,NaN,1117,78,NaN,1,15995,9.00,10.00,4,0,824.142563,0.400000,L,0,0,0,4200.0
19,14,109.0,357987,I,48,48,48,2017-01-01 06:03:00,2017-01-01 06:51:00,2017-01-01 06:51:00,2017-01-01 05:58:00,5,2.0,NaN,1099,91,NaN,1,6292,3.00,4.00,2,0,3259.695637,1.250000,O,0,0,1,3200.0
20,15,322.0,21806,I,31,31,31,2017-01-01 06:09:00,2017-01-01 06:40:00,2017-01-01 06:40:00,2017-01-01 06:04:00,5,1.0,NaN,1043,95,NaN,1,16705,8.00,9.00,4,0,1793.529072,1.250000,L,0,0,1,3200.0
21,16,112.0,309753,T,78,78,78,2017-01-01 06:32:00,2017-01-01 07:50:00,2017-01-01 07:50:00,2017-01-01 06:32:00,0,NaN,1048.0,1095,101,NaN,1,5600,4.00,5.00,2,0,6983.166032,1.250000,O,0,0,1,2400.0
22,17,172.0,44083,I,28,28,28,2017-01-01 06:57:00,2017-01-01 07:25:00,2017-01-01 07:25:00,2017-01-01 06:51:00,6,2.0,NaN,1069,74,NaN,1,43071,9.80,10.20,5,0,509.939365,1.250000,R,0,0,1,5200.0
23,18,145.0,348163,O,0,0,0,2017-01-01 07:00:00,2017-01-01 07:00:00,2017-01-01 07:00:00,2017-01-01 07:00:00,0,1.0,NaN,4031,97,NaN,1,2829,3.80,4.20,1,2,3172.727886,0.100000,O,0,1,1,1800.0
24,23,155.0,26565,O,10,10,10,2017-01-01 07:30:00,2017-01-01 07:40:00,2017-01-01 07:40:00,2017-01-01 07:30:00,0,1.0,NaN,1063,86,NaN,1,4165,5.00,6.00,1,0,4457.150095,0.100000,O,0,1,1,2400.0
25,22,322.0,340618,I,36,36,36,2017-01-01 07:34:00,2017-01-01 08:10:00,2017-01-01 08:10:00,2017-01-01 07:28:00,6,1.0,NaN,1008,82,NaN,1,6732,5.00,6.00,2,0,1861.778785,0.100000,O,0,1,1,3200.0
26,21,104.0,47546,I,29,29,29,2017-01-01 07:36:00,2017-01-01 08:05:00,2017-01-01 08:05:00,2017-01-01 07:32:00,4,2.0,NaN,1108,76,NaN,1,16705,8.00,9.00,4,0,1280.935152,0.100000,R,0,1,1,3200.0
27,24,145.0,513873,O,10,10,10,2017-01-01 07:40:00,2017-01-01 07:50:00,2017-01-01 07:50:00,2017-01-01 07:40:00,0,1.0,NaN,1057,67,NaN,1,4294,3.20,4.80,1,0,3711.097290,0.100000,O,0,1,1,1800.0
28,25,106.0,57134,O,20,20,20,2017-01-01 07:45:00,2017-01-01 08:05:00,2017-01-01 08:05:00,2017-01-01 07:32:00,13,2.0,NaN,1118,79,NaN,1,17068,8.70,9.00,4,0,1074.674469,0.100000,O,0,1,1,3200.0
29,19,155.0,362395,I,30,30,30,2017-01-01 07:50:00,2017-01-01 08:20:00,2017-01-01 08:20:00,2017-01-01 07:45:00,5,2.0,NaN,1066,102,NaN,1,6701,4.00,5.00,2,0,1764.932475,0.100000,R,0,1,1,2400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40135,32192,109.0,362395,O,10,10,10,2017-12-31 12:50:00,2017-12-31 13:00:00,2017-12-31 13:00:00,2017-12-31 12:50:00,0,1.0,NaN,1065,82,NaN,1,6701,4.50,6.00,2,0,4797.765159,7.216667,O,0,0,1,3200.0
40136,32193,163.0,42544,O,18,18,18,2017-12-31 13:02:00,2017-12-31 13:20:00,2017-12-31 13:20:00,2017-12-31 12:52:00,10,2.0,NaN,1079,79,NaN,1,42020,10.00,10.00,5,0,1502.675679,7.900000,O,0,0,1,4200.0
40137,39702,172.0,543098,O,15,15,15,2017-12-31 13:25:00,2017-12-31 13:40:00,2017-12-31 13:40:00,2017-12-31 13:07:00,18,2.0,NaN,1071,86,NaN,2,39643,10.00,11.80,5,0,539.508563,7.900000,O,0,0,1,5200.0
40138,32194,171.0,543098,O,15,15,15,2017-12-31 13:25:00,2017-12-31 13:40:00,2017-12-31 13:40:00,2017-12-31 13:07:00,18,2.0,NaN,1071,86,NaN,2,39643,10.00,11.80,5,0,539.508563,7.900000,O,0,0,1,5200.0
40139,32196,106.0,3158,O,18,18,18,2017-12-31 14:02:00,2017-12-31 14:20:00,2017-12-31 14:20:00,2017-12-31 14:02:00,0,1.0,NaN,1081,83,NaN,1,14807,7.00,7.00,3,0,8239.767208,7.372881,O,0,0,1,3200.0
40140,32195,155.0,374016,O,10,10,10,2017-12-31 14:10:00,2017-12-31 14:20:00,2017-12-31 14:20:00,2017-12-31 14:00:00,10,2.0,NaN,1074,67,NaN,1,9991,5.00,7.00,2,0,1328.895016,7.372881,O,0,0,1,2400.0
40141,32197,112.0,543179,O,15,15,15,2017-12-31 14:15:00,2017-12-31 14:30:00,2017-12-31 14:30:00,2017-12-31 14:15:00,0,1.0,NaN,1058,85,NaN,1,4822,4.00,5.00,1,0,3879.059264,7.372881,O,0,0,1,2400.0
40142,39703,322.0,393061,O,10,10,10,2017-12-31 14:20:00,2017-12-31 14:30:00,2017-12-31 14:30:00,2017-12-31 14:20:00,0,1.0,NaN,1041,88,NaN,2,18108,6.00,7.00,4,0,1676.948494,7.372881,O,0,0,1,3200.0
40143,32200,321.0,393061,O,10,10,10,2017-12-31 14:20:00,2017-12-31 14:30:00,2017-12-31 14:30:00,2017-12-31 14:20:00,0,1.0,NaN,1041,88,NaN,2,18108,6.00,7.00,4,0,1676.948494,7.372881,O,0,0,1,3200.0
40144,32199,145.0,48844,T,35,35,35,2017-12-31 14:25:00,2017-12-31 15:00:00,2017-12-31 15:00:00,2017-12-31 14:25:00,0,1.0,1042.0,1119,61,NaN,1,4151,4.00,5.00,1,0,3824.426279,7.372881,L,1,0,1,1800.0
40145,32198,165.0,61042,T,45,45,45,2017-12-31 14:25:00,2017-12-31 15:10:00,2017-12-31 15:10:00,2017-12-31 14:25:00,0,2.0,1109.0,1070,96,NaN,1,15995,10.00,10.00,4,0,1043.759332,7.372881,R,1,0,1,4200.0
40146,32201,153.0,996483,O,30,30,30,2017-12-31 15:00:00,2017-12-31 15:30:00,2017-12-31 15:30:00,2017-12-31 15:00:00,0,2.0,NaN,1094,48,NaN,1,6566,7.00,8.00,2,0,3066.636532,6.085106,O,0,0,1,2400.0
40147,32202,106.0,22780,O,30,30,30,2017-12-31 15:10:00,2017-12-31 15:40:00,2017-12-31 15:40:00,2017-12-31 15:10:00,0,2.0,NaN,1117,102,NaN,1,14796,7.00,8.00,3,0,824.142563,6.085106,O,0,0,1,3200.0
40148,32204,112.0,483222,O,10,10,10,2017-12-31 15:20:00,2017-12-31 15:30:00,2017-12-31 15:30:00,2017-12-31 15:20:00,0,1.0,NaN,1033,87,NaN,1,6379,4.50,5.20,2,0,2964.240695,6.085106,L,0,0,1,2400.0
40149,32203,163.0,935522,O,25,55,40,2017-12-31 15:25:00,2017-12-31 15:50:00,2017-12-31 16:20:00,2017-12-31 15:25:00,0,2.0,NaN,1103,79,NaN,2,27072,10.00,10.00,4,0,3846.700144,6.085106,O,0,0,1,3300.0
40150,39704,155.0,935522,O,25,55,40,2017-12-31 15:25:00,2017-12-31 15:50:00,2017-12-31 16:20:00,2017-12-31 15:25:00,0,2.0,NaN,1103,79,NaN,2,27072,10.00,10.00,4,0,3846.700144,6.085106,O,0,0,1,3300.0
40151,32205,145.0,532614,O,15,15,15,2017-12-31 16:05:00,2017-12-31 16:20:00,2017-12-31 16:20:00,2017-12-31 16:05:00,0,1.0,NaN,4052,88,NaN,1,3080,4.00,5.00,1,2,3015.412064,3.500000,O,0,0,1,1800.0
40152,32206,112.0,946303,O,15,15,15,2017-12-31 16:05:00,2017-12-31 16:20:00,2017-12-31 16:20:00,2017-12-31 16:05:00,0,1.0,NaN,4031,92,NaN,1,1997,5.00,6.00,1,2,3172.727886,3.500000,O,0,0,1,2400.0
40153,32207,155.0,389838,T,35,35,35,2017-12-31 16:55:00,2017-12-31 17:30:00,2017-12-31 17:30:00,2017-12-31 16:55:00,0,2.0,1118.0,1078,85,NaN,1,2982,3.00,4.00,1,0,2099.257537,3.500000,O,1,0,1,2400.0
40154,32208,112.0,335169,O,6,6,6,2017-12-31 17:04:00,2017-12-31 17:10:00,2017-12-31 17:10:00,2017-12-31 17:04:00,0,1.0,NaN,1032,83,NaN,1,3770,3.30,4.60,1,0,3067.608458,2.000000,R,1,0,1,2400.0
40155,32213,163.0,389838,O,8,8,8,2017-12-31 17:42:00,2017-12-31 17:50:00,2017-12-31 17:50:00,2017-12-31 17:24:00,18,2.0,NaN,1078,85,NaN,1,2982,3.00,4.00,1,0,1123.044526,2.000000,O,0,0,1,4200.0
40156,32210,106.0,490482,O,20,20,20,2017-12-31 17:50:00,2017-12-31 18:10:00,2017-12-31 18:10:00,2017-12-31 17:50:00,0,1.0,NaN,1062,87,NaN,1,6861,5.00,6.00,2,0,4286.866006,2.000000,O,0,0,1,3200.0
40157,32211,165.0,542989,O,20,20,20,2017-12-31 18:00:00,2017-12-31 18:20:00,2017-12-31 18:20:00,2017-12-31 17:54:00,6,2.0,NaN,1118,102,NaN,1,2981,5.00,6.00,1,0,1074.674469,2.000000,O,0,0,1,4200.0
40158,32209,171.0,49271,O,15,15,15,2017-12-31 18:15:00,2017-12-31 18:30:00,2017-12-31 18:30:00,2017-12-31 18:15:00,0,2.0,NaN,1069,48,NaN,1,47259,9.00,10.00,6,0,509.939365,2.000000,R,1,0,1,5200.0
40159,32212,163.0,21415,O,10,10,10,2017-12-31 18:30:00,2017-12-31 18:40:00,2017-12-31 18:40:00,2017-12-31 18:12:00,18,2.0,NaN,1077,75,NaN,1,13246,7.00,8.00,3,0,931.118669,2.000000,L,1,0,1,4200.0
40160,32214,145.0,940925,O,15,15,15,2017-12-31 18:55:00,2017-12-31 19:10:00,2017-12-31 19:10:00,2017-12-31 18:55:00,0,1.0,NaN,1030,92,NaN,1,1780,3.05,5.25,1,0,3348.820680,2.000000,O,0,0,1,1800.0
40161,32215,321.0,543063,O,35,35,35,2017-12-31 19:45:00,2017-12-31 20:20:00,2017-12-31 20:20:00,2017-12-31 19:32:00,13,2.0,NaN,1054,61,NaN,2,36272,7.00,8.00,5,0,3432.562503,1.650000,O,0,0,0,1825.5
40162,39705,451.0,543063,O,35,35,35,2017-12-31 19:45:00,2017-12-31 20:20:00,2017-12-31 20:20:00,2017-12-31 19:32:00,13,2.0,NaN,1054,61,NaN,2,36272,7.00,8.00,5,0,3432.562503,1.650000,O,0,0,0,1825.5
40163,32216,106.0,48844,O,10,10,10,2017-12-31 20:40:00,2017-12-31 20:50:00,2017-12-31 20:50:00,2017-12-31 20:32:00,8,2.0,NaN,1119,94,NaN,1,4151,4.00,5.00,1,0,1325.273091,0.400000,L,1,0,0,3200.0
40164,32217,171.0,61042,O,15,15,15,2017-12-31 21:05:00,2017-12-31 21:20:00,2017-12-31 21:20:00,2017-12-31 20:53:00,12,2.0,NaN,1070,83,NaN,1,15995,10.00,10.00,4,0,380.865875,0.600000,O,0,0,0,5200.0

In [252]:
size = len(df)
tug_from = pd.Series([None] * size)
dic = {101:-1,
 104:-1,
 106:-1,
 108:-1,
 109:-1,
 112:-1,
 143.0:-1,
 145.0:-1,
 151.0:-1,
 152.0:-1,
 153.0:-1,
 155.0:-1,
 162.0:-1,
 163.0:-1,
 165.0:-1,
 171.0:-1,
 172.0:-1,
 181.0:-1,
 241.0:-1,
 245.0:-1,
 303.0:-1,
 306.0:-1,
 308.0:-1,
 321.0:-1,
 322.0:-1,
 401.0:-1,
 451.0:-1,
 568.0:-1}
df_tug = df.tug.get_values()
last = pd.Series([None] * size)

def metch_move_time():
    i = 0
    while i < size:
        if dic[df_tug[i]] == -1:
            dic[df_tug[i]] = i
            last[i] = -1
        elif dic[df_tug[i]] != -1:
            last[i] = df.place2[dic[df_tug[i]]]
            dic[df_tug[i]] = i
            
        i+=1

In [253]:
metch_move_time()

In [254]:
last.columns = "last"
ndf = pd.concat((df,last.rename('last')),axis = 1)
ndf.dropna(subset = ['last'])

,index,tug,ship_no,sailing_status,min_work_time,max_work_time,mean_work_time,start_time,min_end_time,max_end_time,pilot_ready_time,pilot_wait_time,port,place1,place2,pilot1,pilot2,tug_cnt,total_weight,front_weight,back_weight,weight_level,pier_info,dist,wind,park,reverse,seven,day,avg_hp,last
0,0,109.0,50091,O,4,4,4,2017-01-01 00:26:00,2017-01-01 00:30:00,2017-01-01 00:30:00,2017-01-01 00:26:00,0,1.0,NaN,1066,100,NaN,1,6094,6.00,7.00,2,0,4968.093286,0.150000,O,0,0,0,3200.0,-1
1,1,321.0,308684,I,52,52,52,2017-01-01 01:38:00,2017-01-01 02:30:00,2017-01-01 02:30:00,2017-01-01 01:34:00,4,1.0,NaN,1058,82,NaN,1,16232,6.00,7.00,4,0,3879.059264,1.000000,O,0,0,0,3200.0,-1
2,2,171.0,46698,I,27,27,27,2017-01-01 01:38:00,2017-01-01 02:05:00,2017-01-01 02:05:00,2017-01-01 01:30:00,8,2.0,NaN,1079,74,NaN,1,27968,10.00,10.00,4,0,1502.675679,1.000000,L,0,0,0,5200.0,-1
3,5,165.0,376574,O,10,10,10,2017-01-01 02:05:00,2017-01-01 02:15:00,2017-01-01 02:15:00,2017-01-01 01:48:00,17,2.0,NaN,1099,93,NaN,1,2440,5.20,6.00,1,0,3259.695637,0.750000,O,0,0,0,4200.0,-1
4,32219,171.0,57126,I,24,29,26,2017-01-01 02:16:00,2017-01-01 02:40:00,2017-01-01 02:45:00,2017-01-01 02:11:00,5,2.0,NaN,1109,98,76.0,2,108069,11.50,11.70,8,0,1033.162198,0.750000,R,0,0,0,5200.0,1079
5,4,172.0,57126,I,24,29,26,2017-01-01 02:16:00,2017-01-01 02:40:00,2017-01-01 02:45:00,2017-01-01 02:11:00,5,2.0,NaN,1109,98,76.0,2,108069,11.50,11.70,8,0,1033.162198,0.750000,R,0,0,0,5200.0,-1
6,32218,109.0,326585,I,34,34,34,2017-01-01 02:21:00,2017-01-01 02:55:00,2017-01-01 02:55:00,2017-01-01 02:16:00,5,2.0,NaN,1102,102,NaN,2,8562,4.00,5.00,2,0,2785.267130,0.750000,O,0,0,0,3700.0,1066
7,3,163.0,326585,I,34,34,34,2017-01-01 02:21:00,2017-01-01 02:55:00,2017-01-01 02:55:00,2017-01-01 02:16:00,5,2.0,NaN,1102,102,NaN,2,8562,4.00,5.00,2,0,2785.267130,0.750000,O,0,0,0,3700.0,-1
8,8,165.0,1066,O,17,17,17,2017-01-01 02:43:00,2017-01-01 03:00:00,2017-01-01 03:00:00,2017-01-01 02:29:00,14,2.0,NaN,1076,97,NaN,1,4165,3.00,4.00,1,0,995.490209,0.750000,O,0,0,0,4200.0,1099
9,7,171.0,356204,I,42,42,42,2017-01-01 02:58:00,2017-01-01 03:40:00,2017-01-01 03:40:00,2017-01-01 02:53:00,5,2.0,NaN,1105,67,NaN,2,31534,6.00,8.00,5,0,2073.646410,0.750000,L,1,0,0,5200.0,1109
10,32220,172.0,356204,I,42,42,42,2017-01-01 02:58:00,2017-01-01 03:40:00,2017-01-01 03:40:00,2017-01-01 02:53:00,5,2.0,NaN,1105,67,NaN,2,31534,6.00,8.00,5,0,2073.646410,0.750000,L,1,0,0,5200.0,1109
11,6,145.0,348163,T,38,38,38,2017-01-01 03:02:00,2017-01-01 03:40:00,2017-01-01 03:40:00,2017-01-01 03:02:00,0,NaN,1028.0,4031,79,NaN,1,2829,3.60,4.20,1,2,508.713096,0.750000,O,0,0,0,1800.0,-1
12,9,163.0,2607,O,12,12,12,2017-01-01 03:48:00,2017-01-01 04:00:00,2017-01-01 04:00:00,2017-01-01 03:48:00,0,1.0,NaN,1064,70,NaN,1,17751,7.00,8.00,4,0,4627.450322,0.750000,L,1,0,0,4200.0,1102
13,12,109.0,25313,O,26,31,28,2017-01-01 04:24:00,2017-01-01 04:50:00,2017-01-01 04:55:00,2017-01-01 04:11:00,13,2.0,NaN,1117,80,NaN,2,17887,7.00,8.00,4,0,824.142563,0.850000,O,0,0,0,3700.0,1102
14,32222,165.0,25313,O,26,31,28,2017-01-01 04:24:00,2017-01-01 04:50:00,2017-01-01 04:55:00,2017-01-01 04:11:00,13,2.0,NaN,1117,80,NaN,2,17887,7.00,8.00,4,0,824.142563,0.850000,O,0,0,0,3700.0,1076
15,11,171.0,43184,I,36,41,38,2017-01-01 04:59:00,2017-01-01 05:35:00,2017-01-01 05:40:00,2017-01-01 04:52:00,7,2.0,NaN,1065,88,NaN,2,20569,9.20,9.50,4,0,1931.993135,0.850000,R,0,0,0,5200.0,1105
16,32221,172.0,43184,I,36,41,38,2017-01-01 04:59:00,2017-01-01 05:35:00,2017-01-01 05:40:00,2017-01-01 04:52:00,7,2.0,NaN,1065,88,NaN,2,20569,9.20,9.50,4,0,1931.993135,0.850000,R,0,0,0,5200.0,1105
17,10,245.0,364401,I,19,19,19,2017-01-01 05:01:00,2017-01-01 05:20:00,2017-01-01 05:20:00,2017-01-01 04:57:00,4,1.0,NaN,1045,61,NaN,1,2479,3.60,4.00,1,0,2059.012837,0.400000,O,0,0,0,2400.0,-1
18,13,163.0,35629,I,29,29,29,2017-01-01 05:31:00,2017-01-01 06:00:00,2017-01-01 06:00:00,2017-01-01 05:24:00,7,2.0,NaN,1117,78,NaN,1,15995,9.00,10.00,4,0,824.142563,0.400000,L,0,0,0,4200.0,1064
19,14,109.0,357987,I,48,48,48,2017-01-01 06:03:00,2017-01-01 06:51:00,2017-01-01 06:51:00,2017-01-01 05:58:00,5,2.0,NaN,1099,91,NaN,1,6292,3.00,4.00,2,0,3259.695637,1.250000,O,0,0,1,3200.0,1117
20,15,322.0,21806,I,31,31,31,2017-01-01 06:09:00,2017-01-01 06:40:00,2017-01-01 06:40:00,2017-01-01 06:04:00,5,1.0,NaN,1043,95,NaN,1,16705,8.00,9.00,4,0,1793.529072,1.250000,L,0,0,1,3200.0,-1
21,16,112.0,309753,T,78,78,78,2017-01-01 06:32:00,2017-01-01 07:50:00,2017-01-01 07:50:00,2017-01-01 06:32:00,0,NaN,1048.0,1095,101,NaN,1,5600,4.00,5.00,2,0,6983.166032,1.250000,O,0,0,1,2400.0,-1
22,17,172.0,44083,I,28,28,28,2017-01-01 06:57:00,2017-01-01 07:25:00,2017-01-01 07:25:00,2017-01-01 06:51:00,6,2.0,NaN,1069,74,NaN,1,43071,9.80,10.20,5,0,509.939365,1.250000,R,0,0,1,5200.0,1065
23,18,145.0,348163,O,0,0,0,2017-01-01 07:00:00,2017-01-01 07:00:00,2017-01-01 07:00:00,2017-01-01 07:00:00,0,1.0,NaN,4031,97,NaN,1,2829,3.80,4.20,1,2,3172.727886,0.100000,O,0,1,1,1800.0,4031
24,23,155.0,26565,O,10,10,10,2017-01-01 07:30:00,2017-01-01 07:40:00,2017-01-01 07:40:00,2017-01-01 07:30:00,0,1.0,NaN,1063,86,NaN,1,4165,5.00,6.00,1,0,4457.150095,0.100000,O,0,1,1,2400.0,-1
25,22,322.0,340618,I,36,36,36,2017-01-01 07:34:00,2017-01-01 08:10:00,2017-01-01 08:10:00,2017-01-01 07:28:00,6,1.0,NaN,1008,82,NaN,1,6732,5.00,6.00,2,0,1861.778785,0.100000,O,0,1,1,3200.0,1043
26,21,104.0,47546,I,29,29,29,2017-01-01 07:36:00,2017-01-01 08:05:00,2017-01-01 08:05:00,2017-01-01 07:32:00,4,2.0,NaN,1108,76,NaN,1,16705,8.00,9.00,4,0,1280.935152,0.100000,R,0,1,1,3200.0,-1
27,24,145.0,513873,O,10,10,10,2017-01-01 07:40:00,2017-01-01 07:50:00,2017-01-01 07:50:00,2017-01-01 07:40:00,0,1.0,NaN,1057,67,NaN,1,4294,3.20,4.80,1,0,3711.097290,0.100000,O,0,1,1,1800.0,4031
28,25,106.0,57134,O,20,20,20,2017-01-01 07:45:00,2017-01-01 08:05:00,2017-01-01 08:05:00,2017-01-01 07:32:00,13,2.0,NaN,1118,79,NaN,1,17068,8.70,9.00,4,0,1074.674469,0.100000,O,0,1,1,3200.0,-1
29,19,155.0,362395,I,30,30,30,2017-01-01 07:50:00,2017-01-01 08:20:00,2017-01-01 08:20:00,2017-01-01 07:45:00,5,2.0,NaN,1066,102,NaN,1,6701,4.00,5.00,2,0,1764.932475,0.100000,R,0,1,1,2400.0,1063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40135,32192,109.0,362395,O,10,10,10,2017-12-31 12:50:00,2017-12-31 13:00:00,2017-12-31 13:00:00,2017-12-31 12:50:00,0,1.0,NaN,1065,82,NaN,1,6701,4.50,6.00,2,0,4797.765159,7.216667,O,0,0,1,3200.0,1077
40136,32193,163.0,42544,O,18,18,18,2017-12-31 13:02:00,2017-12-31 13:20:00,2017-12-31 13:20:00,2017-12-31 12:52:00,10,2.0,NaN,1079,79,NaN,1,42020,10.00,10.00,5,0,1502.675679,7.900000,O,0,0,1,4200.0,1120
40137,39702,172.0,543098,O,15,15,15,2017-12-31 13:25:00,2017-12-31 13:40:00,2017-12-31 13:40:00,2017-12-31 13:07:00,18,2.0,NaN,1071,86,NaN,2,39643,10.00,11.80,5,0,539.508563,7.900000,O,0,0,1,5200.0,1115
40138,32194,171.0,543098,O,15,15,15,2017-12-31 13:25:00,2017-12-31 13:40:00,2017-12-31 13:40:00,2017-12-31 13:07:00,18,2.0,NaN,1071,86,NaN,2,39643,10.00,11.80,5,0,539.508563,7.900000,O,0,0,1,5200.0,1115
40139,32196,106.0,3158,O,18,18,18,2017-12-31 14:02:00,2017-12-31 14:20:00,2017-12-31 14:20:00,2017-12-31 14:02:00,0,1.0,NaN,1081,83,NaN,1,14807,7.00,7.00,3,0,8239.767208,7.372881,O,0,0,1,3200.0,1118
40140,32195,155.0,374016,O,10,10,10,2017-12-31 14:10:00,2017-12-31 14:20:00,2017-12-31 14:20:00,2017-12-31 14:00:00,10,2.0,NaN,1074,67,NaN,1,9991,5.00,7.00,2,0,1328.895016,7.372881,O,0,0,1,2400.0,1118
40141,32197,112.0,543179,O,15,15,15,2017-12-31 14:15:00,2017-12-31 14:30:00,2017-12-31 14:30:00,2017-12-31 14:15:00,0,1.0,NaN,1058,85,NaN,1,4822,4.00,5.00,1,0,3879.059264,7.372881,O,0,0,1,2400.0,1062
40142,39703,322.0,393061,O,10,10,10,2017-12-31 14:20:00,2017-12-31 14:30:00,2017-12-31 14:30:00,2017-12-31 14:20:00,0,1.0,NaN,1041,88,NaN,2,18108,6.00,7.00,4,0,1676.948494,7.372881,O,0,0,1,3200.0,1118
40143,32200,321.0,393061,O,10,10,10,2017-12-31 14:20:00,2017-12-31 14:30:00,2017-12-31 14:30:00,2017-12-31 14:20:00,0,1.0,NaN,1041,88,NaN,2,18108,6.00,7.00,4,0,1676.948494,7.372881,O,0,0,1,3200.0,1042
40144,32199,145.0,48844,T,35,35,35,2017-12-31 14:25:00,2017-12-31 15:00:00,2017-12-31 15:00:00,2017-12-31 14:25:00,0,1.0,1042.0,1119,61,NaN,1,4151,4.00,5.00,1,0,3824.426279,7.372881,L,1,0,1,1800.0,4031
40145,32198,165.0,61042,T,45,45,45,2017-12-31 14:25:00,2017-12-31 15:10:00,2017-12-31 15:10:00,2017-12-31 14:25:00,0,2.0,1109.0,1070,96,NaN,1,15995,10.00,10.00,4,0,1043.759332,7.372881,R,1,0,1,4200.0,1087
40146,32201,153.0,996483,O,30,30,30,2017-12-31 15:00:00,2017-12-31 15:30:00,2017-12-31 15:30:00,2017-12-31 15:00:00,0,2.0,NaN,1094,48,NaN,1,6566,7.00,8.00,2,0,3066.636532,6.085106,O,0,0,1,2400.0,1118
40147,32202,106.0,22780,O,30,30,30,2017-12-31 15:10:00,2017-12-31 15:40:00,2017-12-31 15:40:00,2017-12-31 15:10:00,0,2.0,NaN,1117,102,NaN,1,14796,7.00,8.00,3,0,824.142563,6.085106,O,0,0,1,3200.0,1081
40148,32204,112.0,483222,O,10,10,10,2017-12-31 15:20:00,2017-12-31 15:30:00,2017-12-31 15:30:00,2017-12-31 15:20:00,0,1.0,NaN,1033,87,NaN,1,6379,4.50,5.20,2,0,2964.240695,6.085106,L,0,0,1,2400.0,1058
40149,32203,163.0,935522,O,25,55,40,2017-12-31 15:25:00,2017-12-31 15:50:00,2017-12-31 16:20:00,2017-12-31 15:25:00,0,2.0,NaN,1103,79,NaN,2,27072,10.00,10.00,4,0,3846.700144,6.085106,O,0,0,1,3300.0,1079
40150,39704,155.0,935522,O,25,55,40,2017-12-31 15:25:00,2017-12-31 15:50:00,2017-12-31 16:20:00,2017-12-31 15:25:00,0,2.0,NaN,1103,79,NaN,2,27072,10.00,10.00,4,0,3846.700144,6.085106,O,0,0,1,3300.0,1074
40151,32205,145.0,532614,O,15,15,15,2017-12-31 16:05:00,2017-12-31 16:20:00,2017-12-31 16:20:00,2017-12-31 16:05:00,0,1.0,NaN,4052,88,NaN,1,3080,4.00,5.00,1,2,3015.412064,3.500000,O,0,0,1,1800.0,1119
40152,32206,112.0,946303,O,15,15,15,2017-12-31 16:05:00,2017-12-31 16:20:00,2017-12-31 16:20:00,2017-12-31 16:05:00,0,1.0,NaN,4031,92,NaN,1,1997,5.00,6.00,1,2,3172.727886,3.500000,O,0,0,1,2400.0,1033
40153,32207,155.0,389838,T,35,35,35,2017-12-31 16:55:00,2017-12-31 17:30:00,2017-12-31 17:30:00,2017-12-31 16:55:00,0,2.0,1118.0,1078,85,NaN,1,2982,3.00,4.00,1,0,2099.257537,3.500000,O,1,0,1,2400.0,1103
40154,32208,112.0,335169,O,6,6,6,2017-12-31 17:04:00,2017-12-31 17:10:00,2017-12-31 17:10:00,2017-12-31 17:04:00,0,1.0,NaN,1032,83,NaN,1,3770,3.30,4.60,1,0,3067.608458,2.000000,R,1,0,1,2400.0,4031
40155,32213,163.0,389838,O,8,8,8,2017-12-31 17:42:00,2017-12-31 17:50:00,2017-12-31 17:50:00,2017-12-31 17:24:00,18,2.0,NaN,1078,85,NaN,1,2982,3.00,4.00,1,0,1123.044526,2.000000,O,0,0,1,4200.0,1103
40156,32210,106.0,490482,O,20,20,20,2017-12-31 17:50:00,2017-12-31 18:10:00,2017-12-31 18:10:00,2017-12-31 17:50:00,0,1.0,NaN,1062,87,NaN,1,6861,5.00,6.00,2,0,4286.866006,2.000000,O,0,0,1,3200.0,1117
40157,32211,165.0,542989,O,20,20,20,2017-12-31 18:00:00,2017-12-31 18:20:00,2017-12-31 18:20:00,2017-12-31 17:54:00,6,2.0,NaN,1118,102,NaN,1,2981,5.00,6.00,1,0,1074.674469,2.000000,O,0,0,1,4200.0,1070
40158,32209,171.0,49271,O,15,15,15,2017-12-31 18:15:00,2017-12-31 18:30:00,2017-12-31 18:30:00,2017-12-31 18:15:00,0,2.0,NaN,1069,48,NaN,1,47259,9.00,10.00,6,0,509.939365,2.000000,R,1,0,1,5200.0,1071
40159,32212,163.0,21415,O,10,10,10,2017-12-31 18:30:00,2017-12-31 18:40:00,2017-12-31 18:40:00,2017-12-31 18:12:00,18,2.0,NaN,1077,75,NaN,1,13246,7.00,8.00,3,0,931.118669,2.000000,L,1,0,1,4200.0,1078
40160,32214,145.0,940925,O,15,15,15,2017-12-31 18:55:00,2017-12-31 19:10:00,2017-12-31 19:10:00,2017-12-31 18:55:00,0,1.0,NaN,1030,92,NaN,1,1780,3.05,5.25,1,0,3348.820680,2.000000,O,0,0,1,1800.0,4052
40161,32215,321.0,543063,O,35,35,35,2017-12-31 19:45:00,2017-12-31 20:20:00,2017-12-31 20:20:00,2017-12-31 19:32:00,13,2.0,NaN,1054,61,NaN,2,36272,7.00,8.00,5,0,3432.562503,1.650000,O,0,0,0,1825.5,1041
40162,39705,451.0,543063,O,35,35,35,2017-12-31 19:45:00,2017-12-31 20:20:00,2017-12-31 20:20:00,2017-12-31 19:32:00,13,2.0,NaN,1054,61,NaN,2,36272,7.00,8.00,5,0,3432.562503,1.650000,O,0,0,0,1825.5,1037
40163,32216,106.0,48844,O,10,10,10,2017-12-31 20:40:00,2017-12-31 20:50:00,2017-12-31 20:50:00,2017-12-31 20:32:00,8,2.0,NaN,1119,94,NaN,1,4151,4.00,5.00,1,0,1325.273091,0.400000,L,1,0,0,3200.0,1062
40164,32217,171.0,61042,O,15,15,15,2017-12-31 21:05:00,2017-12-31 21:20:00,2017-12-31 21:20:00,2017-12-31 20:53:00,12,2.0,NaN,1070,83,NaN,1,15995,10.00,10.00,4,0,380.865875,0.600000,O,0,0,0,5200.0,1069

In [256]:
dist_pier = pd.read_excel('data/complete_dis_meter.xlsx', index_col=1)
dist_pier
def fetch_dist(row):
    if row['sailing_status'] == 'I':
        if pd.isna(row['last']) or int(row['last']) not in dist_pier.index:
            return None
        return dist_pier.loc[int(row['last']), 9001] if int(row['port']) == 1 else dist_pier.loc[int(row['last']), 9002]
    
    elif row['sailing_status'] == 'O':
        if pd.isna(row['last']) and pd.isna(row['place2']) or int(row['last']) not in dist_pier.index or int(row['place2']) not in dist_pier.index:
            return None
        return dist_pier.loc[int(row['last']), int(row['place2'])]
    
    elif row['sailing_status'] == 'T':
        if pd.isna(row['place1']) or pd.isna(row['last']) or int(row['place1']) not in dist_pier.index or int(row['last']) not in dist_pier.index:
            return None
        return dist_pier.loc[int(row['last']), int(row['place1'])]

    
ndf['move_dist'] = ndf.apply(fetch_dist, axis=1)
# ndf = ndf.dropna(subset = ['move_dist'])
ndf['move_min'] = (ndf['move_dist'] / 18520) * 60
ndf
writer = pd.ExcelWriter('data/main1010.xlsx')
ndf.to_excel(writer,'Sheet1')
writer.save()